\newpage
\renewcommand\partcontent{PETTERSON 1817-1944}

\hypertarget{14}{}

14. Torparen [PETTER ANDERS FREDRIKSSON KATT](#1) från Katthemman, som kom dit som måg, Katternö by,  
  född 3/4 1817, död 3/1 1893 i lunginflammation  
  Gift I 1845 med Greta Mattsdotter,  
  född 8/11 1821, död 27/11 1868 i vattsot.  
  Gift II 27/9 1873 med Anna Lisa Johansdotter Granholm,  
  född 18/11 1827 i Nykarleby, död 29/7 1892 i Pedersöre

#### Barn i I giftet:

141. [Johan Fredrik Pettersson](#141),  
  född 29/5 1846, död 3/12 1920 Jakobstad.  
  Gift 25/1 1874 med Sofia Karlsdotter Kristola,  
  född 7/8 1846, död 30/7 1929.

142. [Jakob Petterson](#142) (Tages farfar),  
  född 8/7 1849, död 20/10 1915 i Åbo.  
  Gift 7/12 1876 med [Maria Lovisa Hermans](#h13),  
  född 8/11 1846, död 13/6 1898 i Åbo.  

143. [Anna Lovisa](#143), född 15/3 1852, död 2/7 1924 i Jomala.  
  Gift 19/7 1884 med Anders Johan Granholm (styvmors son),  
  född 17/11 1854, död 12/2 1924 i Jomala.

144. Gustaf, född 6/12 1854, död 1854.

145. Catarina, född 6/12 1854, död 1855.

146. Petter Anders Pettersson,  
  född 9/8 1857 död 1/9 1935 i Brownsville, Washington.  
  Flyttade 1879 till St.Petersburgh, 1893 till USA.  

147. [Anna Sofia](#147), född 9/8 1857, död 14/11 1944 i Helsingfors.  
  Gift 6/9 1896 med timmerman Johan Johansson Westlin,  
  född 14/6 1862 i Oravais, död 29/4 1943 i Helsingfors.

148. Matts, född 6/6 1860, död 22/1 1861. (+ en tvilling).

149. [Gustaf](#149),  
  född 21/11 1862, död 11/4 1942 i Brownville, Washington.  
  Gift I med Matilda Holm, född 24/3 1861, död 3/9 1918.  
  Gift II med Lina Holm, född  8/10 1872. (syster till förra hustrun)
